docker:
  image: yegor256/rultor-image:1.19.0
install: |-
  sudo gem install texsc:0.6.0
  sudo gem install texqc:0.6.0
  sudo apt-get -y update
  sudo apt-get -y install aspell
  sudo apt-get -y install ghostscript inkscape
  sudo tlmgr option repository ctan
  sudo tlmgr --verify-repo=none update --self
  sudl tlmgr --verify-repo=none install $(cut -d' ' -f2 DEPENDS.txt | uniq)
  sudo tlmgr --verify-repo=none update l3build docshots iexec
merge:
  script: |-
    l3build check
release:
  pre: false
  script: |-
    l3build tag ${tag}
    l3build ctan --show-log-on-error
    texsc
    texqc
    git commit -am "version set to ${tag}"
    echo 'y' | l3build upload --halt-on-error
