name: make
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: rultor-image
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          make
